### PR TITLE
Laba2 pull request

### PR DESCRIPTION
**Pull request by artegful**

### CODE REVIEW

**Review by nastik1811 — CHANGES_REQUESTED** [review]
- Why do you use `<picture>` tag for icons?
- Logo and app name (in case they're not clickable) should not be included to <nav> element
- Where do `<a>time</a>` `<a>words</a>` links lead?
- Using "English" and "dark" as links to the settings is a bad approach. And I don't understand what do you mean by <--settings--> in the header then.

**Comment by nastik1811** [comment]
??
image

**Comment by nastik1811** [comment]
Why `<a>`? 
image

**Comment by nastik1811** [comment]
Why two links for settings?

image

**Comment by nastik1811** [comment]
What will happen on click? Or is it just a caption? 
image

**Comment by nastik1811** [comment]
> Why two links for settings?
> 
> image

ah, I've just noticed that the second one leads to the game

**Comment by nastik1811** [comment]
Are you ok with `7` ?

**Comment by artegful** [comment]
> Are you ok with `7` ?

Okay

**Review by nastik1811 — APPROVED** [review]

**Comment by nastik1811** [comment]
Why did you ignore the other comments? :/

**Comment by artegful** [comment]
> Why did you ignore the other comments? :/

Oops, sorry

**Comment by artegful** [comment]
> What will happen on click? Or is it just a caption? image

That's just a caption

**Comment by artegful** [comment]
> Why `<a>`? image

I'm not really sure, how that's going to interact with js, so I've simply used a

**Comment by artegful** [comment]
> ?? image

I didn't know how to mark this one, by that I meant a clickable div (with border, border-radius, background-color representing color for the body)

**Pull request merged**
